##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/isfmrtkuac/public_html
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R files $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R contactform $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH
    /bin/cp .cpanel.yml $DEPLOYPATH
